name: Run scrapers daily

on:
  schedule:
    - cron: '0 22 * * *'  # every day at 2 AM UTC
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chrome (headless browser for Selenium)
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable

      - name: Run Amazon scraper
        run: echo -e "mobiles\niphone 13" | python scrapers/_amazon.py

      - name: Run Noon scraper
        run: echo -e "iphone 13\nmobiles" | python scrapers/noon.py

      - name: Run Jumia scraper
        run: echo -e "iphone 13\nmobiles" | python scrapers/jumia.py

      - name: Run BTech scraper
        run: echo -e "iphone 13\nmobiles" | python scrapers/btech.py

      - name: Run 2B scraper
        run: echo -e "iphone 13\nmobiles" | python scrapers/_2b.py
